#!/usr/bin/env bash
# Copy the compiled report PDF into site/ so static hosts serve it directly.
# Intended as the build command for Cloudflare Pages (or any static host).
#
# Usage (from repo root):
#   ./site/build.sh
#
# Cloudflare Pages configuration:
#   Build command:          ./site/build.sh
#   Build output directory: site
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Rebuild the paper if pdflatex is available; otherwise use the committed PDF.
if command -v pdflatex >/dev/null 2>&1; then
  (cd "$REPO_ROOT/paper" && ./build.sh)
fi

cp "$REPO_ROOT/paper/main.pdf" "$SCRIPT_DIR/report.pdf"
echo "copied report.pdf ($(du -h "$SCRIPT_DIR/report.pdf" | cut -f1))"

# Bake build metadata (commit SHA + dates) into site/build-info.js so the
# navbar can render "last updated <date>". Falls back to "unknown" if the
# build is happening outside a git checkout.
git_sha="$(git -C "$REPO_ROOT" rev-parse --short HEAD 2>/dev/null || echo unknown)"
git_long_sha="$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
commit_iso="$(git -C "$REPO_ROOT" log -1 --format=%cI 2>/dev/null || echo unknown)"
build_iso="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

cat > "$SCRIPT_DIR/build-info.js" <<JS
// Auto-generated by site/build.sh. Do not edit by hand.
export const BUILD_INFO = {
  commit:    "${git_sha}",
  commitUrl: "https://github.com/jaredraycoleman/evacuation-claude/commit/${git_long_sha}",
  commitISO: "${commit_iso}",
  buildISO:  "${build_iso}"
};
JS
echo "wrote build-info.js ($git_sha @ $commit_iso)"
